Sprint 1
djokcik/praktikum-go-devops pull request #3
Opened 2021-12-22 18:11 UTC by djokcik

2021-12-22 18:31 UTC, djokcik commented on internal/agent/agent_metrics.go
> +	return []AgentMetric{
не уверен, что это правильно в мире GO)

2021-12-22 23:54 UTC, Bazys requested changes
Хорошо струтурированный проект!
Проделан большой объем работы, особенно для всех метрик. Созданы струтуры и интерфейсы под каждую.
Осталось добавить пройденную тему в теории, а именно работа с контекстом.
И факультативно, sync.RWMutex для storage struct

2021-12-22 23:54 UTC, Bazys commented on cmd/agent/main.go
> +const reportInterval = 10
в данном случае лучше сразу указать в виде time.Duration, т.е. константу вида 10*time.Second
в таком случе всегда будет понятно для чего это константа, не только из названия но и из ее типа.
плюс в дальнейшем не надо будет прозводить эти умножения

2021-12-22 23:54 UTC, Bazys commented on cmd/agent/main.go
> +	go helpers.SetTicker(metricAgent.SendToServer, reportInterval)
не используется context.
в случае остановки агента во время отправики обновлений на сервер, нам необходимо отменять запрос. Иначе сервер будет бесконечно ожидать продолжения.

2021-12-22 23:54 UTC, Bazys commented on cmd/agent/main.go
> +	"github.com/Jokcik/praktikum-go-devops/internal/agent"
опечатка?
аккаунт на гитхабе не совпадает с пакетом.
сейчас это не страшно, но в жизни из-за этого можно много времени потерять.

2021-12-22 23:54 UTC, Bazys commented on internal/agent/agent_metrics.go
> +	return []AgentMetric{
в данном случае просто инициализация массива дефолтными значениями. норм.
Просто часто в жизни приходится необходимо будет быть уверенным что ты в этот момент не пытаешься разименовать nill указатель

2021-12-22 23:54 UTC, Bazys commented on internal/agent/mocks/AgentMetric.go
> +// Code generated by mockery v2.9.4. DO NOT EDIT.
аж моки, да еще с использованием mockery.
Это кртуо!

2021-12-22 23:54 UTC, Bazys commented on internal/agent/report_server.go
> +		req, err := http.NewRequest(http.MethodPost, url, nil)
вот здесь можно вызывать запрос с контекстом

2021-12-22 23:54 UTC, Bazys commented on internal/metric/metrics.go
> +type Gauge float64
реально необходимо вводить сustom type?

2021-12-22 23:54 UTC, Bazys commented on static/listMetrics.html
> +<!DOCTYPE html>
подключить шаблоны, это абсолютно правильная мысль!

2021-12-22 23:54 UTC, Bazys commented on internal/server/storage/model/database.go
> +	CounterMapMetric map[string]metric.Counter
в теории курса было сказано, что в принципе работа со структурами в горутинах проблем не вызывает.
Но посокльку ты достаточно продвинутый студент, рекомендую в структуру добавить sync.RWMutex
и лочить перед записью в мапы

2021-12-23 08:02 UTC, Bazys commented on internal/metric/metrics.go
> +type Gauge float64
ну в общем тут на твое усмотрение.

2021-12-23 15:22 UTC, Bazys commented on cmd/agent/main.go
> +	cancel()
сейчас устроит, но в будущих инкриментах делай вызов с defer сразу просле объявления

2021-12-23 16:09 UTC, djokcik commented on cmd/agent/main.go
> +	cancel()
точно, еще не привык)

2021-12-23 17:45 UTC, Bazys requested changes

2021-12-23 17:45 UTC, Bazys commented on internal/agent/agent_metrics.go
> +	Ctx             context.Context
а вот это плохая практика!
в теории было сказано про это.
контекст не должен быть полем структуры!
контекст должен быть первым аргументом вызываемой функции!

2021-12-23 19:01 UTC, djokcik commented on internal/agent/agent_metrics.go
> +	Ctx             context.Context
проглядел(
исправил

2021-12-23 19:04 UTC, Bazys approved these changes

2021-12-23 19:09 UTC, Bazys commented
мёржишь сам после апрува

2021-12-27 18:38 UTC, merged